import assert from "node:assert/strict";
import test from "node:test";
import vm from "node:vm";

import { renderDashboardPage, renderLoginPage } from "../src/ui.js";

test("login page uses Vietnamese copy and no fake support links", () => {
  const html = renderLoginPage();

  assert.match(html, /href="\/assets\/admin-tailwind\.css\?v=20260611-ui5"/);
  assert.match(html, /<body class="tailwind-ui login-screen server-login">/);
  assert.match(html, /<html lang="vi">/);
  assert.match(html, />\s*Tài khoản\s*</);
  assert.match(html, />\s*Mật khẩu\s*</);
  assert.match(html, />Đăng nhập<\/button>/);
  assert.match(html, /Sai tài khoản hoặc mật khẩu/);
  assert.match(html, /id="languageSelect"/);
  assert.match(html, /value="en">English/);
  assert.doesNotMatch(html, /Forgot password\?|Request access|Sign in/);
  assert.doesNotMatch(html, /class="form-links"/);
});

test("dashboard inline browser script is valid JavaScript", () => {
  const html = renderDashboardPage({ publicUrl: "https://example.test" });
  const script = html.match(/<script>([\s\S]*)<\/script>/)?.[1];

  assert.ok(script);
  assert.doesNotThrow(() => new vm.Script(script, { filename: "dashboard-inline.js" }));
  assert.match(html, /data-monitor-detail=/);
  assert.match(html, /function openMonitoringDetails\(/);
  assert.match(html, /function restoreMonitoringDetails\(/);
  assert.match(html, /function refreshRemoteTelemetry\(/);
  assert.match(html, /target\.id === "refreshTelemetryBtn" && selectedId\) refreshRemoteTelemetry\(\)/);
  assert.doesNotMatch(html, /target\.id === "refreshTelemetryBtn" && selectedId\) openRemote\(selectedId\)/);
});

test("dashboard renders inverter control actions", () => {
  const html = renderDashboardPage({ publicUrl: "https://example.test" });

  assert.match(html, /data-tab-target="inverterControlTab"/);
  assert.match(html, /id="inverterControlTab"/);
  assert.match(html, /data-control-action="start"/);
  assert.match(html, /data-control-action="stop"/);
  assert.match(html, /data-control-action="reboot"/);
  assert.match(html, /data-control-action="clear_power_limit"/);
  assert.match(html, /id="powerLimitForm"/);
  assert.match(html, /id="powerLimitValue" type="number" min="0" max="100"/);
  assert.match(html, /id="controlScheduleMode"/);
  assert.match(html, /id="controlScheduleUntil"/);
  assert.match(html, /id="controlScheduleEndTime"/);
  assert.match(html, /id="controlScheduleSummary"/);
  assert.match(html, /id="controlTransport"/);
  assert.match(html, />Tailscale direct<\/option>/);
  assert.doesNotMatch(html, />Cloud queue<\/option>/);
  assert.match(html, /value="daily"/);
  assert.match(html, /value="weekly"/);
  assert.match(html, /data-schedule-weekday="1"/);
  assert.match(html, /function collectPowerLimitTiming\(/);
  assert.match(html, /function updatePowerLimitValueConstraints\(/);
  assert.match(html, /function collectControlSchedule\(/);
  assert.match(html, /function activeControlTransport\(/);
  assert.match(html, /\/api\/gateways\/" \+ encodeURIComponent\(selectedId\) \+ "\/tailscale\/control/);
  assert.match(html, /function isControlCapableDevice\(/);
  assert.match(html, /function hasBuiltInControlProfile\(/);
  assert.match(html, /function deviceIdentityText\(/);
  assert.match(html, /data-field="baudRate" type="number" min="1" step="1"/);
  assert.match(html, /data-field="dataBits" type="number" min="5" max="8" step="1"/);
  assert.match(html, /data-field="address" type="number" min="0" max="65535"/);
  assert.match(html, /data-field="length" type="number" min="1" max="125"/);
  assert.match(html, /data-template="' \+ index \+ '" data-field="protocol"/);
  assert.match(html, /commandScheduleLabel\(command\)/);
  assert.match(html, /\/api\/gateways\/" \+ encodeURIComponent\(selectedId\) \+ "\/commands/);
});

test("dashboard renders shared template library editor", () => {
  const html = renderDashboardPage({ publicUrl: "https://example.test" });

  assert.match(html, /data-tab-target="libraryTab"/);
  assert.match(html, /id="libraryTab"/);
  assert.match(html, /id="templateLibrary"/);
  assert.match(html, /id="addTemplateBtn"/);
  assert.match(html, /id="saveTemplatesBtn"/);
  assert.match(html, /\/api\/device-templates/);
});

test("dashboard starts at site list and remote disconnect returns home", () => {
  const html = renderDashboardPage({ publicUrl: "https://example.test" });

  assert.match(html, /href="\/assets\/admin-tailwind\.css\?v=20260611-ui5"/);
  assert.match(html, /<body class="tailwind-ui admin-screen server-admin">/);
  assert.match(html, /id="homePageTitle">Site/);
  assert.match(html, /data-home-target="homeOverviewPanel"/);
  assert.deepEqual([...html.matchAll(/data-home-target="([^"]+)"/g)].map((match) => match[1]), ["homeOverviewPanel"]);
  assert.match(html, /const mode = iec104\.mode \|\| "server"/);
  assert.match(html, /escapeHtml\(mode\)/);
  assert.doesNotMatch(html, /id="homeGatewayPanel"/);
  assert.doesNotMatch(html, /id="homeTelemetryPanel"/);
  assert.doesNotMatch(html, /id="homeConfigPanel"/);
  assert.doesNotMatch(html, /id="gatewayTableBody"/);
  assert.match(html, /id="gatewayHomeGrid" class="gateway-grid"/);
  assert.match(html, /data-delete-gateway=/);
  assert.match(html, /id="addManualGatewayBtn"/);
  assert.match(html, /name="tailscaleHost"/);
  assert.match(html, /id="openTailscaleUiBtn"/);
  assert.match(html, /id="remoteAccessHost"/);
  assert.match(html, /id="saveRemoteAccessBtn"/);
  assert.match(html, /function remoteAccessUiUrl\(/);
  assert.match(html, /function openGatewayRemote\(/);
  assert.match(html, /\/gateways\/" \+ encodeURIComponent\(gatewayId\) \+ "\/remote/);
  assert.doesNotMatch(html, /data-open-tailscale-gateway/);
  assert.doesNotMatch(html, /openRemote\(target\.dataset\.remoteGateway\)/);
  assert.match(html, /\/api\/gateways\/" \+ encodeURIComponent\(selectedId\)/);
  assert.match(html, /\/api\/gateways\/" \+ encodeURIComponent\(gatewayId\)/);
  assert.match(html, /id="remoteDisconnectBtn"/);
  assert.match(html, />Về danh sách site</);
  assert.doesNotMatch(html, /Disconnection/);
  assert.match(html, /Chưa có site/);
  assert.match(html, /gateway\.id/);
  assert.match(html, /Tailscale IP\/host/);
  assert.doesNotMatch(html, /id="logoutBtn"/);
  assert.doesNotMatch(html, /id="backHomeBtn"/);
  assert.doesNotMatch(html, /id="remoteRefreshBtn"/);
  assert.match(html, /#remoteView \{/);
  assert.match(html, /class="sidebar-logo"/);
  assert.match(html, /\.sidebar-logo,\s*\.brand-mark \{/);
  assert.match(html, /\.sidebar-logo img,\s*\.brand-mark img \{/);
  assert.match(html, /id="sidebarLanStatus"[\s\S]*?<use href="#icon-network"><\/use>/);
  assert.doesNotMatch(html, /<span class="brand-mark"><img src="\/logo\/logo-smallsize\.png"/);
  assert.match(html, /id="adminLanguageSelect"/);
  assert.doesNotMatch(html, /id="remoteLanguageSelect"/);
  assert.match(html, /function applyAdminLanguage\(/);
  assert.match(html, /target\?\.id === "adminLanguageSelect"/);
  assert.match(html, /localStorage\.setItem\("adminLanguage"/);
  assert.match(html, /href="#stationDeviceOverviewSubtab" data-tab-target="generalInformation"/);
  assert.match(html, /Trạng thái gateway, telemetry và cấu hình IPC/);
  assert.match(html, /stationDeviceOverviewSubtab: \["Tổng quan"/);
  assert.doesNotMatch(html, /id="overviewSubtab"/);
  assert.doesNotMatch(html, /data-subtab-target="overviewSubtab"/);
  assert.match(html, /class="menu-button"[^>]+data-tab-target="generalInformation"/);
  assert.match(html, /id="deviceMonitoring" class="home-panel monitoring-panel"/);
  assert.match(html, /class="monitor-toolbar"/);
  assert.match(html, /monitor-status/);
  assert.match(html, /monitor-meta/);
  assert.match(html, /monitor-key-grid/);
  assert.match(html, /id="refreshTelemetryBtn"/);
  assert.match(html, /id="controlHistoryBody"/);
  assert.match(html, /function cancelCommand\(/);
  assert.match(html, /data-cancel-command/);
  assert.match(html, /method: "DELETE"/);
  assert.doesNotMatch(html, /id="commandRefreshBtn"/);
  assert.match(html, /id="refreshRuntimeBtn"/);
  assert.match(html, /id="storageSyncBody"/);
  assert.match(html, /id="logsEventsBody"/);
  assert.match(html, /id="systemGatewayId"/);
  assert.match(html, /data-restart-gateway/);
  assert.match(html, /id="configurationTopology" class="topology-tree topology-tree-compact"/);
  assert.match(html, /id="syncTemplatesBtn"/);
  assert.doesNotMatch(html, /id="refreshTemplatesBtn"/);
  assert.match(html, /function syncTemplateLibrary\(/);
  assert.doesNotMatch(html, /function refreshTemplateLibrary\(/);
  assert.doesNotMatch(html, />Function<\/th>/);
  assert.doesNotMatch(html, />Length<\/th>/);
  assert.doesNotMatch(html, />Unit<\/th>/);
  assert.doesNotMatch(html, /Protocol <select/);
  assert.doesNotMatch(html, /id="remoteStorageBody"/);
  assert.doesNotMatch(html, /id="remoteEventsBody"/);
  assert.doesNotMatch(html, /id="remoteSystemGatewayId"/);
  assert.match(html, /id="status" class="status"/);
  assert.doesNotMatch(html, /id="statusDot"/);
  assert.match(html, /target\.id === "remoteDisconnectBtn"/);
  assert.match(html, /backHome\(\)/);
  assert.match(html, /id="stationDeviceOverviewSubtab" class="subtab-panel active"/);
  assert.match(html, /id="dashboardTopology" class="topology-tree"/);
  assert.match(html, /id="topOkCount"/);
  assert.match(html, /id="topErrorCount"/);
  assert.match(html, /id="topWarningCount"/);
  assert.match(html, /id="topLossCount"/);
  assert.match(html, /data-subtab-target="stationsSubtab"/);
  assert.match(html, /href="#iec104Subtab" data-tab-target="iec104Tab"/);
  assert.match(html, /id="iec104Subtab"/);
  assert.match(html, /id="applyEvnIec104DefaultsBtn"/);
  assert.doesNotMatch(html, /id="evnRequiredRegistersBody"/);
  assert.match(html, /id="iec104EvnStation"/);
  assert.match(html, /id="generateEvnIec104Btn"/);
  assert.match(html, /id="iec104Enabled" type="checkbox" checked/);
  assert.match(html, /type="hidden" value="server"/);
  assert.match(html, /id="iec104EvnSourcesBody"/);
  assert.match(html, /data-evn-field="register"/);
  assert.match(html, /Register từng thiết bị/);
  assert.match(html, /data-evn-override-field="powerRegister"/);
  assert.doesNotMatch(html, /data-field="evnRole"/);
  assert.match(html, /data-field="evnEnabled"/);
  assert.match(html, /multiple size=/);
  assert.doesNotMatch(html, /id="addIec104PointBtn"/);
  assert.doesNotMatch(html, /id="addIec104ControlBtn"/);
  assert.doesNotMatch(html, /id="iec104ControlsBody"/);
  assert.doesNotMatch(html, /iec104Simulator/);
  assert.doesNotMatch(html, /iec104SelectTimeout/);
  assert.match(html, /target\.id === "applyEvnIec104DefaultsBtn"/);
  assert.match(html, /target\.id === "generateEvnIec104Btn"/);
  assert.match(html, /function collectStations\(\)/);
  assert.match(html, /function syncStationDeviceMembership\(\)/);
  assert.match(html, /function mountStandaloneIec104Tab\(\)/);
  assert.match(html, /data-tab-target="iec104Tab"/);
  assert.match(html, /data-tab-target="storageSyncTab"/);
  assert.match(html, /data-tab-target="logsEventsTab"/);
  assert.match(html, /data-tab-target="systemTab"/);
});
